version: '3'
services:
  testsuite:
    image: "denvazh/gatling"
    command: -m
    environment:
      # Använd sys.env("ENDPOINT") i simuleringarna för att få detta värde.
      - ENDPOINT=https://test.esb.ntjp.se/vp/clinicalprocess/healthcond/description/GetCareDocumentation/2/rivtabp21
    volumes:
      - ./conf:/opt/gatling/conf
      - ./user-files:/opt/gatling/user-files
      - ./results:/opt/gatling/results
  recorder:
    image: "denvazh/gatling"
    # bash är inte istallerat i containern, så måste explict köra sh
    entrypoint: ["sh", "/opt/gatling/bin/recorder.sh"]
    # För exempelkommandon:
    # docker-compose run --rm recorder --help
    command: -cli true -lp 8000
    ports:
      - "8000:8000"
    volumes:
      - ./user-files:/opt/gatling/user-files
